### ISSUE TITLE
the data file construct?

### ISSUE THREAD

**Issue by kunyaoli** [AbhinavJhanwar/vgg_regressor#11]
I have some question about the input data file. now i have some images in img dir ,and a csv file inculde the image path and lable(regression lable), just like this :

---img
   ---xxx.jpg
   ---xxx.jpg
---data.csv

if i want run your code , what should i do in my own data file? 

thank you!~

**Comment by kunyaoli** [comment]
> 

- 

1. 

> 
> 
> I have some question about the input data file. now i have some images in img dir ,and a csv file inculde the image path and lable(regression lable), just like this :
> 
> ---img
> ---xxx.jpg
> ---xxx.jpg
> ---data.csv
> 
> if i want run your code , what should i do in my own data file?
> 
> thank you!~

---img
------xxx.jpg
------xxx02.jpg
---data.csv

**Comment by AbhinavJhanwar** [comment]
In data.csv just create two columns. first column with say header 'image_name' and second column with header say 'target'. In 'image_name' add image names like xxx.jpg in first row and value of regression target in 'target' column and so on.
Now update training_config.conf file as following-
1) specify path of this csv file in  csv_file variable
2) specify path of img folder in images_dir variable
3) specify path of any pretrained model to use in pretrained_weights otherwise leave as None after updating configuration file 4) run the python script main.py to start training.
I hope this solves your problem. Best of luck !!
